export const testProducts = [
  {
    _id: "1",
    storeName: "Denner",
    title: "Zucchetti",
    price: 0.75,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.15, incrQty: 100, incrStr: "0.15/100g" },
    quantity: { qtyAmount: 500, qtyStr: "500g" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "2",
    storeName: "Coop",
    title: "Äpfel Boskop Klasse I",
    price: 3.6,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 3.6, incrQty: 1, incrStr: "3.60/1kg" },
    quantity: { qtyAmount: 1, qtyStr: "1kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "3",
    storeName: "Coop",
    title: "Bio Zucchetti",
    price: 3.4,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.68, incrQty: 100, incrStr: "0.68/100kg" },
    quantity: { qtyAmount: 500, qtyStr: "500kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "4",
    storeName: "Coop",
    title: "Knoblauch 1 Stuck",
    price: 0.55,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.55, incrQty: 1, incrStr: "0.55/1ST" },
    quantity: { qtyAmount: 1, qtyStr: "1ST" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "5",
    storeName: "Coop",
    title: "Zwieblen rot",
    price: 0.8,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.16, incrQty: 100, incrStr: "0.16/100g" },
    quantity: { qtyAmount: 500, qtyStr: "500g" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "6",
    storeName: "Migros",
    title: "Migros Zucchetti",
    price: 3,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 3, incrQty: 100, incrStr: "0.60/100kg" },
    quantity: { qtyAmount: 500, qtyStr: "500kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "7",
    storeName: "Migros",
    title: "Migros Zwieblen gelb",
    price: 1,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.2, incrQty: 100, incrStr: "0.20/100g" },
    quantity: { qtyAmount: 500, qtyStr: "500g" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "8",
    storeName: "Migros",
    title: "Knoblauch 2 Stucke",
    price: 0.9,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.45, incrQty: 1, incrStr: "0.45/1ST" },
    quantity: { qtyAmount: 2, qtyStr: "2ST" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "9",
    storeName: "Migros",
    title: "Bananen",
    price: 2.8,
    categories: ["fruechte-gemuese"],
    increment: { ncrPrice: 2.8, incrQty: 1, incrStr: "2.80/1kg" },
    quantity: { qtyAmount: 1, qtyStr: "1kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "10",
    storeName: "Denner",
    title: "Denner Bananen",
    price: 1.4,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 1.4, incrQty: 1, incrStr: "1.40/1kg" },
    quantity: { qtyAmount: 1, qtyStr: "1kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "11",
    storeName: "Coop",
    title: "Zucchetti",
    price: 3,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.6, incrQty: 100, incrStr: "0.60/100kg" },
    quantity: { qtyAmount: 500, qtyStr: "500kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "12",
    storeName: "Migros",
    title: "Äpfel",
    price: 3.4,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 3.4, incrQty: 1, incrStr: "3.40/1kg" },
    quantity: { qtyAmount: 1, qtyStr: "1kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "13",
    storeName: "Denner",
    title: "Zwieblen weiss",
    price: 1.5,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.3, incrQty: 100, incrStr: "0.30/100g" },
    quantity: { qtyAmount: 500, qtyStr: "500g" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "14",
    storeName: "Denner",
    title: "Denner Zwieblen rot",
    price: 0.75,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.15, incrQty: 100, incrStr: "0.15/100g" },
    quantity: { qtyAmount: 500, qtyStr: "500g" },
    favorites: [],
    grocList: [],
  },
];
