export const allProducts = [
  {
    _id: "6299bbc5939c9c82ca84d69d",
    storeName: "Coop",
    title: "Äpfel Boskop Klasse I ca. 1kg",
    brand: "Coop",
    incrementPrice: 3.6,
    incrementQuantity: 1,
    incrementString: "3.60/1kg",
    quantityAmount: 1,
    quantityString: "1kg",
    price: 3.6,
    createdAt: "2022-06-03T07:44:05.591Z",
    updatedAt: "2022-06-03T07:44:05.591Z",
    __v: 0,
    sale: "false",
    productCategory: ["all", "fruechte-gemuese"],
    userFavorite: false,
    onGroceryList: false,
  },
  {
    _id: "6299bc2c939c9c82ca84d69f",
    storeName: "Coop",
    title: "Naturaplan Bio Zucchetti",
    brand: "Coop",
    incrementPrice: 3.4,
    incrementQuantity: 100,
    incrementString: "0.68/100kg",
    quantityAmount: 500,
    quantityString: "500kg",
    price: 3.4,
    createdAt: "2022-06-03T07:45:48.139Z",
    updatedAt: "2022-06-03T07:45:48.139Z",
    __v: 0,
    sale: "false",
    productCategory: ["all", "fruechte-gemuese"],
    userFavorite: false,
    onGroceryList: false,
  },
  {
    _id: "6299bc7e939c9c82ca84d6a1",
    storeName: "Coop",
    title: "Knoblauch 1 Stuck",
    brand: "Coop",
    incrementPrice: 0.55,
    incrementQuantity: 1,
    incrementString: "0.55/1ST",
    quantityAmount: 1,
    quantityString: "1ST",
    price: 0.55,
    createdAt: "2022-06-03T07:47:10.007Z",
    updatedAt: "2022-06-03T07:47:10.007Z",
    __v: 0,
    sale: "true",
    productCategory: ["all", "fruechte-gemuese"],
    userFavorite: false,
    onGroceryList: false,
  },
  {
    _id: "6299bcb9939c9c82ca84d6a3",
    storeName: "Coop",
    title: "Zwieblen rot",
    brand: "Coop",
    incrementPrice: 0.16,
    incrementQuantity: 100,
    incrementString: "0.16/100g",
    quantityAmount: 500,
    quantityString: "500g",
    price: 0.8,
    createdAt: "2022-06-03T07:48:09.924Z",
    updatedAt: "2022-06-03T07:48:09.924Z",
    __v: 0,
    productCategory: ["all", "fruechte-gemuese"],
    sale: "false",
    userFavorite: false,
    onGroceryList: false,
  },
  {
    _id: "629a25441ff2946e636ba79c",
    storeName: "Coop",
    title: "Cervelas 2 Stuck",
    brand: "Coop",
    incrementPrice: 1.18,
    incrementQuantity: 100,
    incrementString: "1.18/100g",
    quantityAmount: 200,
    quantityString: "200g",
    price: 2.35,
    productCategory: ["all", "fleisch-fisch"],
    sale: "false",
    createdAt: "2022-06-03T15:14:12.772Z",
    updatedAt: "2022-06-03T15:14:12.772Z",
    __v: 0,
    userFavorite: false,
    onGroceryList: false,
  },
  {
    storeName: "Migros",
    title: "Cervelas",
    brand: "M-Classic",
    incrementPrice: 0.98,
    incrementQuantity: 100,
    incrementString: "0.98/100g",
    quantityAmount: 200,
    quantityString: "200g",
    price: 1.95,
    productCategory: ["all", "fleisch-fisch"],
    sale: "false",
    _id: "629dd450d91cdfa88778db3e",
    createdAt: "2022-06-06T10:17:52.829Z",
    updatedAt: "2022-06-06T10:17:52.829Z",
    __v: 0,
    userFavorite: false,
    onGroceryList: false,
  },
  {
    storeName: "Migros",
    title: "Bananen",
    brand: "Bio-Fairtrade",
    incrementPrice: 2.8,
    incrementQuantity: 1,
    incrementString: "2.80/1kg",
    quantityAmount: 1,
    quantityString: "1kg",
    price: 2.8,
    productCategory: ["all", "fruechte-gemuese"],
    sale: "false",
    _id: "629dd51cd91cdfa88778db40",
    createdAt: "2022-06-06T10:21:16.807Z",
    updatedAt: "2022-06-06T10:21:16.807Z",
    __v: 0,
    userFavorite: false,
    onGroceryList: false,
  },
  {
    storeName: "Denner",
    title: "Denner Bananen",
    brand: "Denner",
    incrementPrice: 1.4,
    incrementQuantity: 1,
    incrementString: "1.40/1kg",
    quantityAmount: 1,
    quantityString: "1kg",
    price: 1.4,
    productCategory: ["all", "fruechte-gemuese"],
    sale: "false",
    _id: "629dd675d91cdfa88778db41",
    createdAt: "2022-06-06T10:27:01.577Z",
    updatedAt: "2022-06-06T10:27:01.577Z",
    __v: 0,
    userFavorite: false,
    onGroceryList: false,
  },
  {
    storeName: "Denner",
    title: "Denner Meat",
    brand: "Denner",
    incrementPrice: 1.4,
    incrementQuantity: 1,
    incrementString: "1.40/1kg",
    quantityAmount: 1,
    quantityString: "1kg",
    price: 1.4,
    productCategory: ["all", "fleisch-fisch"],
    sale: "false",
    _id: "629dd675d91cdfa88778db42",
    createdAt: "2022-06-06T10:27:01.577Z",
    updatedAt: "2022-06-06T10:27:01.577Z",
    __v: 0,
    userFavorite: false,
    onGroceryList: false,
  },
];

export const user = {
  firstName: "Bryan",
  favoritesList: {
    "629dd675d91cdfa88778db42": {
      storeName: "Denner",
      title: "Denner Meat",
      brand: "Denner",
      incrementPrice: 1.4,
      incrementQuantity: 1,
      incrementString: "1.40/1kg",
      quantityAmount: 1,
      quantityString: "1kg",
      price: 1.4,
      productCategory: ["all", "fleisch-fisch"],
      sale: "false",
      _id: "629dd675d91cdfa88778db42",
      createdAt: "2022-06-06T10:27:01.577Z",
      updatedAt: "2022-06-06T10:27:01.577Z",
      __v: 0,
      userFavorite: true,
      onGroceryList: false,
    },
  },
  groceryList: {
    "6299bc7e939c9c82ca84d6a1": {
      _id: "6299bc7e939c9c82ca84d6a1",
      storeName: "Coop",
      title: "Knoblauch 1 Stuck",
      brand: "Coop",
      incrementPrice: 0.55,
      incrementQuantity: 1,
      incrementString: "0.55/1ST",
      quantityAmount: 1,
      quantityString: "1ST",
      price: 0.55,
      createdAt: "2022-06-03T07:47:10.007Z",
      updatedAt: "2022-06-03T07:47:10.007Z",
      __v: 0,
      sale: "true",
      productCategory: ["all", "fruechte-gemuese"],
      userFavorite: false,
      onGroceryList: true,
    },
  },
};

export const groceryCategories = [
  {
    value: "fruechte-gemuese",
    displayName: "Fr&uuml;chte &amp; Gem&uuml;se",
  },
  {
    value: "milchprodukte-eier",
    displayName: "Milchprodukte &amp; Eier",
  },
  {
    value: "fleisch-fisch",
    displayName: "Fleisch &amp; Fisch",
  },
  {
    value: "brot-backwaren",
    displayName: "Brot &amp; Backwaren",
  },
  {
    value: "getraenke",
    displayName: "Getr&auml;nke",
  },
  {
    value: "vorraete",
    displayName: "Vorr&auml;te",
  },
  {
    value: "suesses-snacks",
    displayName: "S&uuml;sses &amp; Snacks",
  },
  {
    value: "tiefgekuehlte-produkte",
    displayName: "Tiefgek&uuml;hlte &amp; Produkte",
  },
  {
    value: "fertiggerichte",
    displayName: "Fertiggerichte",
  },
];

export const storeNames = ["Coop", "Migros", "Denner"];

// !!!!!!! WITH NEW DB STRUCTURE
export const testProducts = [
  {
    _id: "1",
    store: "Denner",
    title: "Zucchetti",
    price: 3.2,
    categories: ["fruechte-gemuese"],
    increment: {
      incrPrice: 0.64,
      incrQty: 100,
      incrStr: "0.64/100kg",
    },
    quantity: { qtyAmount: 500, qtyStr: "500kg" },
    //  with db, will use User._id('ID') pattern
    //  user._id = string
    favorites: ["1234", "2222"],
    grocList: ["2222"],
  },
  {
    _id: "2",
    storeName: "Coop",
    title: "Äpfel Boskop Klasse I",
    price: 3.6,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 3.6, incrQty: 1, incrStr: "3.60/1kg" },
    quantity: { qtyAmount: 1, qtyStr: "1kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "3",
    storeName: "Coop",
    title: "Bio Zucchetti",
    price: 3.4,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.68, incrQty: 100, incrStr: "0.68/100kg" },
    quantity: { qtyAmount: 500, qtyStr: "500kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "4",
    storeName: "Coop",
    title: "Knoblauch 1 Stuck",
    price: 0.55,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.55, incrQty: 1, incrStr: "0.55/1ST" },
    quantity: { qtyAmount: 1, qtyStr: "1ST" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "5",
    storeName: "Coop",
    title: "Zwieblen rot",
    price: 0.8,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.16, incrQty: 100, incrStr: "0.16/100g" },
    quantity: { qtyAmount: 500, qtyStr: "500g" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "6",
    storeName: "Migros",
    title: "Migros Zucchetti",
    price: 3,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 3, incrQty: 100, incrStr: "0.60/100kg" },
    quantity: { qtyAmount: 500, qtyStr: "500kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "7",
    storeName: "Migros",
    title: "Migros Zwieblen gelb",
    price: 1,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.2, incrQty: 100, incrStr: "0.20/100g" },
    quantity: { qtyAmount: 500, qtyStr: "500g" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "8",
    storeName: "Migros",
    title: "Knoblauch 2 Stucke",
    price: 0.9,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.45, incrQty: 1, incrStr: "0.45/1ST" },
    quantity: { qtyAmount: 2, qtyStr: "2ST" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "9",
    storeName: "Migros",
    title: "Bananen",
    price: 2.8,
    categories: ["fruechte-gemuese"],
    increment: { ncrPrice: 2.8, incrQty: 1, incrStr: "2.80/1kg" },
    quantity: { qtyAmount: 1, qtyStr: "1kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "10",
    storeName: "Denner",
    title: "Denner Bananen",
    price: 1.4,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 1.4, incrQty: 1, incrStr: "1.40/1kg" },
    quantity: { qtyAmount: 1, qtyStr: "1kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "11",
    storeName: "Coop",
    title: "Zucchetti",
    price: 3,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.6, incrQty: 100, incrStr: "0.60/100kg" },
    quantity: { qtyAmount: 500, qtyStr: "500kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "12",
    storeName: "Migros",
    title: "Äpfel",
    price: 3.4,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 3.4, incrQty: 1, incrStr: "3.40/1kg" },
    quantity: { qtyAmount: 1, qtyStr: "1kg" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "13",
    storeName: "Denner",
    title: "Zwieblen weiss",
    price: 1.5,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.3, incrQty: 100, incrStr: "0.30/100g" },
    quantity: { qtyAmount: 500, qtyStr: "500g" },
    favorites: [],
    grocList: [],
  },
  {
    _id: "14",
    storeName: "Denner",
    title: "Denner Zwieblen rot",
    price: 0.75,
    categories: ["fruechte-gemuese"],
    increment: { incrPrice: 0.15, incrQty: 100, incrStr: "0.15/100g" },
    quantity: { qtyAmount: 500, qtyStr: "500g" },
    favorites: [],
    grocList: [],
  },
];

export const testUser1 = {
  _id: "1234",
  name: "Bryan Turner",
  username: "email@email.com",
  password: "hashed password",
  //   in db will use Product._id('ID') pattern
  lists: {
    favorites: ["1"],
    grocList: [],
  },
};

export const testUser2 = {
  _id: "2222",
  name: "Alexandra Wyder",
  username: "email@email.com",
  password: "hashed password",
  lists: {
    favorites: ["1"],
    grocList: ["1"],
  },
};
