export const storeNames = ["Coop", "Migros", "Denner"];

// !!!!!!! WITH NEW DB STRUCTURE
export const testProducts = [
  {
    _id: "1",
    storeName: "Denner",
    title: "Zucchetti",
    price: 0.75,
    categories: ["fruechte-gemuese"],
    incrStr: "0.15/100g",
    qtyStr: "500g",
  },
  {
    _id: "2",
    storeName: "Coop",
    title: "Äpfel Boskop Klasse I",
    price: 3.6,
    categories: ["fruechte-gemuese"],
    incrStr: "3.60/1kg",
    qtyStr: "1kg",
  },
  {
    _id: "3",
    storeName: "Coop",
    title: "Bio Zucchetti",
    price: 3.4,
    categories: ["fruechte-gemuese"],
    incrStr: "0.68/100kg",
    qtyStr: "500kg",
  },
  {
    _id: "4",
    storeName: "Coop",
    title: "Knoblauch 1 Stuck",
    price: 0.55,
    categories: ["fruechte-gemuese"],
    incrStr: "0.55/1ST",
    qtyStr: "1ST",
  },
  {
    _id: "5",
    storeName: "Coop",
    title: "Zwieblen rot",
    price: 0.8,
    categories: ["fruechte-gemuese"],
    incrStr: "0.16/100g",
    qtyStr: "500g",
  },
  {
    _id: "6",
    storeName: "Migros",
    title: "Migros Zucchetti",
    price: 3,
    categories: ["fruechte-gemuese"],
    incrStr: "0.60/100kg",
    qtyStr: "500kg",
  },
  {
    _id: "7",
    storeName: "Migros",
    title: "Migros Zwieblen gelb",
    price: 1,
    categories: ["fruechte-gemuese"],
    incrStr: "0.20/100g",
    qtyStr: "500g",
  },
  {
    _id: "8",
    storeName: "Migros",
    title: "Knoblauch 2 Stucke",
    price: 0.9,
    categories: ["fruechte-gemuese"],
    incrStr: "0.45/1ST",
    qtyStr: "2ST",
  },
  {
    _id: "9",
    storeName: "Migros",
    title: "Bananen",
    price: 2.8,
    categories: ["fruechte-gemuese"],
    incrStr: "2.80/1kg",
    qtyStr: "1kg",
  },
  {
    _id: "10",
    storeName: "Denner",
    title: "Denner Bananen",
    price: 1.4,
    categories: ["fruechte-gemuese"],
    incrStr: "1.40/1kg",
    qtyStr: "1kg",
  },
  {
    _id: "11",
    storeName: "Coop",
    title: "Zucchetti",
    price: 3,
    categories: ["fruechte-gemuese"],
    incrStr: "0.60/100kg",
    qtyStr: "500kg",
  },
  {
    _id: "12",
    storeName: "Migros",
    title: "Äpfel",
    price: 3.4,
    categories: ["fruechte-gemuese"],
    incrStr: "3.40/1kg",
    qtyStr: "1kg",
  },
  {
    _id: "13",
    storeName: "Denner",
    title: "Zwieblen weiss",
    price: 1.5,
    categories: ["fruechte-gemuese"],
    incrStr: "0.30/100g",
    qtyStr: "500g",
  },
  {
    _id: "14",
    storeName: "Denner",
    title: "Denner Zwieblen rot",
    price: 0.75,
    categories: ["fruechte-gemuese"],
    incrStr: "0.15/100g",
    qtyStr: "500g",
  },
  {
    _id: "15",
    storeName: "Denner",
    title: "Meat",
    price: 0.75,
    categories: ["fleisch-fisch"],
    incrStr: "0.15/100g",
    qtyStr: "500g",
  },
];

export const testUser1 = {
  _id: "1234",
  name: "Bryan Turner",
  username: "email@email.com",
  password: "hashed password",
  //   in db will use Product._id('ID') pattern
  lists: {
    favorites: [
      {
        _id: "1",
        storeName: "Denner",
        title: "Zucchetti",
        price: 0.75,
        categories: ["fruechte-gemuese"],
        incrStr: "0.15/100g",
        qtyStr: "500g",
      },
    ],
    grocList: [
      {
        _id: "1",
        storeName: "Denner",
        title: "Zucchetti",
        price: 0.75,
        categories: ["fruechte-gemuese"],
        incrStr: "0.15/100g",
        qtyStr: "500g",
      },
    ],
  },
};

export const testUser2 = {
  _id: "2222",
  name: "Alexandra Wyder",
  username: "email@email.com",
  password: "hashed password",
  lists: {
    favorites: ["2"],
    grocList: ["2"],
  },
};
